### ISSUE TITLE
connection refused to local daemon - first example from documentation

### ISSUE THREAD

**Issue by pjgoodall** [canonical/pylxd#383]
The following simple source fails for my local system
``` python
from pylxd import Client
client = Client()
all_containers = client.containers.all()
print(client.containers.all())
```
### lxc installation

The preferred method for installing plxd on ubuntu 18.04 LTS [is to use snap](https://linuxcontainers.org/lxd/getting-started-cli/)

``` bash
% lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

% sudo snap install lxd
% lxd --version
3.20
```

### Python environment installation

Typically people use Anaconda/conda for installing and managing python environments - that is what I do. I use the lighter-weight version [Miniconda](https://docs.conda.io/en/latest/miniconda.html)

I have a [conda virtual environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) configured for working with lxc and pylxd.

This environment is built using an environment.yml file:

``` yml
name: lxc-x11
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - pylint
  - anaconda:python=3
  - pip:
    - pylxd
```

``` bash
% pip show pylxd
Name: pylxd
Version: 2.2.10
Summary: python library for lxd
Home-page: http://www.linuxcontainers.org
Author: Paul Hummer and others (see CONTRIBUTORS.rst)
Author-email: lxc-devel@lists.linuxcontainers.org
License: UNKNOWN
Location: /home/peterg/miniconda3/envs/lxc-x11/lib/python3.8/site-packages
Requires: requests-unixsocket, cryptography, pbr, ws4py, requests-toolbelt, python-dateutil, six, requests
Required-by:
(lxc-x11)
```

*** I have attached a copy of `conda list` from this environment as [conda-list.txt](https://github.com/lxc/pylxd/files/4201937/conda-list.txt)

## Problem demonstration

from the [pylxd documentation on readthedocs](https://pylxd.readthedocs.io/en/latest/usage.html), I created the following python source for a local daemon. I don't believe i need any certificate to perform this action. 

``` python
from pylxd import Client
client = Client()

all_containers = client.containers.all()

print(client.containers.all())
```

lxc can list containers from the command-line, no-problem.

``` bash
% lxc list
+---------+---------+------+------+-----------+-----------+
|  NAME   |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS |
+---------+---------+------+------+-----------+-----------+
| byobu   | STOPPED |      |      | CONTAINER | 0         |
+---------+---------+------+------+-----------+-----------+
| gui1804 | STOPPED |      |      | CONTAINER | 1         |
```

If I execute the python source:

``` bash
% python ./pylxd-test.py
Traceback (most recent call last):
  File "/home/peterg/miniconda3/envs/lxc-x11/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/home/peterg/miniconda3/envs/lxc-x11/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/peterg/miniconda3/envs/lxc-x11/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/peterg/miniconda3/envs/lxc-x11/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/peterg/miniconda3/envs/lxc-x11/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/peterg/miniconda3/envs/lxc-x11/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/home/peterg/miniconda3/envs/lxc-x11/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/home/peterg/miniconda3/envs/lxc-x11/lib/python3.8/site-packages/requests_unixsocket/adapters.py", line 41, in connect
    sock.connect(socket_path)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:
[...]
```

*** I have attached the full output from `% python ./pylxd-test.py 2>pylxd-err.txt
` as [pylxd-err.txt](https://github.com/lxc/pylxd/files/4201938/pylxd-err.txt)

## Python 2.7
If I switch to python 2.7 in environment.yml and `conda  env update --prune`. I get a similar error:

```bash
% python --version
Python 2.7.17 :: Anaconda, Inc.

% pip show pylxd  
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. [...]
https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Name: pylxd
Version: 2.2.10
Summary: python library for lxd
Home-page: http://www.linuxcontainers.org
Author: Paul Hummer and others (see CONTRIBUTORS.rst)
Author-email: lxc-devel@lists.linuxcontainers.org
License: UNKNOWN
Location: /home/peterg/miniconda3/envs/lxc-x11/lib/python2.7/site-packages
Requires: python-dateutil, ws4py, pyOpenSSL, requests-unixsocket, pbr, cryptography, six, requests, requests-toolbelt
Required-by: 

%python ./pylxd-test.py 
Traceback (most recent call last):
  File "./pylxd-test.py", line 2, in <module>
    client = Client()
  File "/home/peterg/miniconda3/envs/lxc-x11/lib/python2.7/site-packages/pylxd/client.py", line 315, in __init__
    raise exceptions.ClientConnectionFailed()
pylxd.exceptions.ClientConnectionFailed
```

**Comment by pjgoodall** [comment]
I just installed the same environment within an Ubuntu 18.04 container, ran a nested ubuntu 18.04 container, and ran my test python source.
```
(base) ubuntu@pylxd:~$ conda activate lxc-x11
(lxc-x11) ubuntu@pylxd:~$ python ./pylxd-test.py 
[<pylxd.models.container.Container object at 0x7f62f3726110>]
``` 

So it seems my workstation has some configuration which is incompatible with pylxd. I purposely kept the containers in the above test the same version as the host. Quite distressing - Ayn ideas ?

**Comment by pjgoodall** [comment]
results of `snap info lxd` attached
[snapinfo.txt](https://github.com/lxc/pylxd/files/4202162/snapinfo.txt)

**Comment by pjgoodall** [comment]
I'm going to re-init lxd after `lxd init --dump` and do a diff.

**Comment by ajkavanagh** [comment]
Hi Peter

It'll be the endpoint detection code that's trying to work out whether a package (from repos) or a snap is installed.  The relevant code starts at: https://github.com/lxc/pylxd/blob/master/pylxd/client.py#L296

I suspect (but can't be sure) that you've either still got, or had, a pkg installed version of LXD, and now have a snap installed version, and the detection code is going for the pkg version.  You can override using the `LXD_DIR` env variable (see the above code for an example).

If it's NOT the above, then something else weird is going on.  Let me know how it goes?  Thanks.

**Comment by simondeziel** [comment]
Closing this old issue. The snap detection logic was reworked and has been working reliably AFAIK. If not, please let us know through a fresh issue, thanks.
