### ISSUE TITLE
Remove lxd.tar.xz from history 

### ISSUE THREAD

**Issue by fliiiix** [canonical/pylxd#493]
Would it be possible to remove `lxd.tar.xz` from this repo?

It is pretty easy to do with something like https://rtyley.github.io/bfg-repo-cleaner/,
the only problem is that you need to rewrite history. 
But I would argue it's worth it, since this should never been part of the repo 
and will speed up every clone in the future which is created from this repo.

```
git clone --mirror git@github.com:lxc/pylxd.git
java -jar ~/Downloads/bfg-1.14.0.jar --strip-blobs-bigger-than 50M pylxd.git
```

**Comment by simondeziel** [comment]
Rewriting git history isn't really something we'd consider at this point. A possible workaround is to do a shallow clone:

```
git clone --depth=1 https://github.com/canonical/pylxd.git
```
