### ISSUE TITLE
Outdated ubuntu package

### ISSUE THREAD

**Issue by hadmut** [canonical/pylxd#596]
Hi, 

if this is a repository maintained by canonical itself, I do wonder, why the ubuntu/debian package python3-pylxd is outdated and taken from an an old source that does not even exist anymore: https://github.com/lxd/pylxd

I have opened  a bug on launchpad two months ago, but nobody seems to care about:

https://bugs.launchpad.net/ubuntu/+source/python-pylxd/+bug/2065537

If canonical itself is maintaining pylxd, shouldn't they also update the ubuntu package, or at least remove the outdated package from the package list?

It took me some time to realize that python3-pylxd was not covering all functions and not working well just because it is outdated and taken from an abandoned source repo. 

Additionally, the installation command given in your README does not even work this way under recent Ubuntu versions (on 24.04):

# pip install pylxd
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

So, Ubuntu is asking at the same time to override the deb package with pip, and not to do it. 

Please do make this consistent, functioning, and not self-contradictory. 

regards

**Comment by simondeziel** [comment]
> Hi,
> 
> if this is a repository maintained by canonical itself, I do wonder, why the ubuntu/debian package python3-pylxd is outdated and taken from an an old source that does not even exist anymore: https://github.com/lxd/pylxd

Indeed, that's an old and broken link.

> I have opened a bug on launchpad two months ago, but nobody seems to care about:
> 
> https://bugs.launchpad.net/ubuntu/+source/python-pylxd/+bug/2065537

My bad, I was not subscribed to bugs from this package which TBH, didn't know existed. Also, it's not managed by Canonical per-se, it's coming in from Debian: https://packages.debian.org/source/sid/python-pylxd

I'll try to make contact with the Debian maintainer and see if I can push some updates to it.

> If canonical itself is maintaining pylxd, shouldn't they also update the ubuntu package, or at least remove the outdated package from the package list?

That's not exactly how Ubuntu releases work. Package versions are "frozen" at release time and remain at the same version for the whole lifetime of the release.

> It took me some time to realize that python3-pylxd was not covering all functions and not working well just because it is outdated and taken from an abandoned source repo.
> 
> Additionally, the installation command given in your README does not even work this way under recent Ubuntu versions (on 24.04):
> # pip install pylxd
> 
> error: externally-managed-environment
> 
> × This environment is externally managed ╰─> To install Python packages system-wide, try apt install python3-xyz, where xyz is the package you are trying to install.
> 
> ```
> If you wish to install a non-Debian-packaged Python package,
> create a virtual environment using python3 -m venv path/to/venv.
> Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
> sure you have python3-full installed.
> 
> If you wish to install a non-Debian packaged Python application,
> it may be easiest to use pipx install xyz, which will manage a
> virtual environment for you. Make sure you have pipx installed.
> 
> See /usr/share/doc/python3.12/README.venv for more information.
> ```
> 
> note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages. hint: See PEP 668 for the detailed specification.
> 
> So, Ubuntu is asking at the same time to override the deb package with pip, and not to do it.
> 
> Please do make this consistent, functioning, and not self-contradictory.

Indeed, that's inconsistent but that's coming from 2 different entities so to speak. https://github.com/canonical/pylxd/pull/597 should improve the provided example, please take a look at it.

> regards

Thanks!
