### ISSUE TITLE
I'm currently running a snap lxd 5.21 on centos8 and a pip installed pylxd of version 2.3.1

### ISSUE THREAD

**Issue by Dweller** [canonical/pylxd#602]
When a call lxd.container.create() and one of my device shared mounts is invalid or there is a syntax error in the the Exception raised is NULL but if I debug the script and print response.json() I can see a meaningful error message.

Is there any plans to fix this in a future version of pylxd?

**Comment by simondeziel** [comment]
Please provide a simple reproducer script so that we can easily replicate the issue. Thanks

**Comment by Dweller** [comment]
Apologies my code, my bad...
